### ISSUE TITLE
Is it possible to calculate anchor automatically without sides setting?

### ISSUE THREAD

**Issue by newforrestgump001** [dlibml/yolo-object-detector#3]
Is it possible to calculate anchor automatically without sides setting? 
Thank you in advance!
Since sometimes it is hard to specify the value of sides.

**Comment by arrufat** [comment]
I was thinking about adding a shell script which calls this functions with sane parameters.

Usually, the `--sides` parameters is needed because we don't know the strides the user might have in their network, so we need a way to filter the bounding boxes according to their size, and that is network architecture dependent.

I usually call the program like this:

```bash
./compute_anchors --size 640 \
    --clusters 3 --sides 8 48  \   # for 8×8 stride
    --clusters 3 --sides 32 192 \  # for 16×16 stride
    --clusters 3 --sides 128 768 \ # for 32×32 stride, basically, the rest
    --dataset /path/to/dataset.xml
```

It doesn't matter in which order you put them, it will sort them and use the first appearance of `clusters` with the first appearance of `sides` and so on.

Note that, in the way the program is written right now, it doesn't use the minimum value for the `sides` option... I think we don't need it, but I did when I was writting the program, however it is not used.

Maybe a better option would be to just have a `strides` option, and we should automatically group the bounding boxes that make sense for that stride...

Honestly, I implemented this pretty quickly, so I didn't do a lot of research on how to do it properly. I am open to suggestions.

**Comment by arrufat** [comment]
For the [COCO 2017 train dataset](http://dlib.net/files/data/dlib_coco_annotations_trainval2017.tar.bz2), that command outputs:

```
group #0: 8 - 48
group #1: 32 - 192
group #2: 128 - 768
total number of boxes: 860001
Computing anchors for 272821 samples
  {{13, 14}, {18, 35}, {36, 28}}
  Sample Fraction: 0.317233
  Average IoU:     0.586747
Computing anchors for 377191 samples
  {{54, 58}, {70, 137}, {141, 102}}
  Sample Fraction: 0.438594
  Average IoU:     0.566556
Computing anchors for 209989 samples
  {{293, 156}, {159, 302}, {498, 376}}
  Sample Fraction: 0.244173
  Average IoU:     0.589815

Total Coverage: 1
```

Which are a bit different from [the ones](https://github.com/WongKinYiu/yolov7/blob/44d8ab41780e24eba563b6794371f29db0902271/cfg/training/yolov7.yaml#L8-L10) used in YOLOv4 and YOLOv7, but still they seem reasonable:

```yaml
anchors:
  - [12,16, 19,36, 40,28]  # P3/8
  - [36,75, 76,55, 72,146]  # P4/16
  - [142,110, 192,243, 459,401]  # P5/32
```

**Comment by arrufat** [comment]
You could also call it like this:
```bash
./compute_anchors --size 640 --clusters 9 --sides 8 768 --dataset data/coco_train2017.xml
```

That is, put all boxes in the same group and find 9 clusters automatically, that would output:
```
group #0: 8 - 768
total number of boxes: 860001
Computing anchors for 860001 samples
  {{26, 30}, {77, 81}, {98, 184}, {216, 126}, {164, 327}, {334, 271}, {526, 172}, {322, 496}, {576, 415}}
  Sample Fraction: 1
  Average IoU:     0.525404

Total Coverage: 1
```

And that's basically what the YOLO example program does. However, the problem is that now you don't know which anchors to put in which stride. I would say that `{98, 184}` is too large for an 8×8 stride...

**Comment by newforrestgump001** [comment]
Sincere thanks for your kind help! I got it.
